--liquibase formatted sql

--changeset KorolchukVladislav:1
CREATE TABLE users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city character varying(255),
    email character varying(255),
    first_name character varying(255),
    image character varying(255),
    last_name character varying(255),
    phone character varying(255),
    reg_date character varying(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
    );

--changeset KorolchukVladislav:2
CREATE TABLE ads
(
    ads_author integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ads_pk integer,
    ads_price integer,
    ads_title character varying(255) COLLATE pg_catalog."default",
    ads_user_id integer
    );

--changeset KorolchukVladislav:3
CREATE TABLE comment
(
    comment_author integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at character varying(255),
    pk integer NOT NULL,
    text character varying(255)
);

--changeset KorolchukVladislav:4
CREATE TABLE IF NOT EXISTS public.ads_image
(
    ads_ads_author integer NOT NULL,
    image character varying(255)
    );

--changeset KorolchukVladislav:5
CREATE TABLE IF NOT EXISTS public.image
(
    image_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    image_id_ads bigint,
    image_image character varying(255) COLLATE pg_catalog."default",
    ads_ads_author integer
    )
