--liquibase formatted sql

--changeset KorolchukVladislav:1
create table image
(
    id         bigint generated by default as identity primary key,
    file_size  bigint,
    media_type varchar(255),
    data_image bytea
);

create table users
(
    id                      bigint generated by default as identity primary key,
    first_name              varchar(255),
    last_name               varchar(255),
    email                   varchar(255),
    password_authorizations varchar(255),
    phone                   varchar(255),
    city                    varchar(255),
    reg_date                timestamp,
    image_id                bigint references image (id),
    role_authorizations     varchar(255)
);

create table ad
(
    id          bigint generated by default as identity primary key,
    title       varchar(255),
    description varchar(255),
    price       integer,
    author_id   bigint references users (id),
    image_id    bigint references image (id)
);

create table comment
(
    id           bigint generated by default as identity primary key,
    created_at   varchar(255),
    text_comment varchar(255),
    author_id    bigint references users (id),
    ad_id        bigint references ad (id)
);

